version: '3'
services:
  web-proxy:
    container_name: proxy
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/.env:/app/backend/.env
    restart: unless-stopped
    networks:
      - waredetective-net

networks:
  waredetective-net:
    external: true
